#!/usr/bin/env node

/**
 * login-all.js — Master login script for all job boards
 * 
 * Usage:
 *   node login-all.js              # Login to all platforms
 *   node login-all.js linkedin     # Login to LinkedIn only
 *   node login-all.js indeed       # Login to Indeed only
 *   node login-all.js seek         # Login to SEEK only
 *   node login-all.js --check      # Check all cookie status
 */

const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const PLATFORMS = {
  linkedin: {
    name: 'LinkedIn',
    url: 'https://www.linkedin.com/login',
    profile: '/tmp/chrome-profile-linkedin',
    config: 'config/linkedin.yml',
    detectUrl: /linkedin\.com\/(feed|notifications|mynetwork)/,
  },
  indeed: {
    name: 'Indeed',
    url: 'https://secure.indeed.com/auth',
    profile: '/tmp/chrome-profile-indeed',
    config: 'config/indeed.yml',
    detectUrl: /indeed\.com\//,
  },
  seek: {
    name: 'SEEK',
    url: 'https://www.seek.com.au/account/login',
    profile: '/tmp/chrome-profile-seek',
    config: 'config/seek.yml',
    detectUrl: /seek\.com\.au/,
  },
};

// ─── Cookie management ────────────────────────────────────────────────────

function loadCookies(platform) {
  const configPath = path.join(process.cwd(), PLATFORMS[platform].config);
  if (!fs.existsSync(configPath)) return null;
  
  const yaml = fs.readFileSync(configPath, 'utf8');
  const cookies = [];
  const domain = platform === 'linkedin' ? '.linkedin.com' : 
                 platform === 'indeed' ? '.indeed.com' : '.seek.com.au';
  
  const re = /- name:\s*"([^"]+)"\s*\n\s*value:\s*"([^"]+)"/g;
  let m;
  while ((m = re.exec(yaml)) !== null) {
    cookies.push({ name: m[1], value: m[2], domain });
  }
  
  const exportedMatch = yaml.match(/exportedAt:\s*"([^"]+)"/);
  const exportedAt = exportedMatch?.[1] ? new Date(exportedMatch[1]) : null;
  
  return { cookies, exportedAt };
}

function checkCookieAge(exportedAt) {
  if (!exportedAt) return { valid: false, days: -1 };
  const age = Date.now() - exportedAt.getTime();
  const days = Math.round(age / (24 * 60 * 60 * 1000));
  return { valid: days < 30, days };
}

function saveCookies(platform, cookies) {
  const config = PLATFORMS[platform];
  const domain = platform === 'linkedin' ? '.linkedin.com' : 
                 platform === 'indeed' ? '.indeed.com' : '.seek.com.au';
  
  let yaml = `# ${config.name} Configuration\n`;
  yaml += '# SECURITY: This file is gitignored. Never commit it.\n';
  yaml += `# Generated by login-all.js\n\n`;
  yaml += `${platform}:\n`;
  yaml += '  status: valid\n';
  yaml += `  exportedAt: "${new Date().toISOString()}"\n`;
  yaml += '  cookies:\n';
  
  for (const c of cookies) {
    yaml += `    - name: "${c.name}"\n`;
    yaml += `      value: "${c.value}"\n`;
    yaml += `      domain: "${c.domain || domain}"\n`;
  }
  
  fs.writeFileSync(config.config, yaml);
  return cookies.length;
}

// ─── Login flow ────────────────────────────────────────────────────────────

async function loginPlatform(platform) {
  const config = PLATFORMS[platform];
  
  console.log(`\n🔐 ${config.name} Login`);
  console.log('─'.repeat(40));
  
  const context = await chromium.launchPersistentContext(config.profile, {
    headless: false,
    channel: 'chrome',
    args: ['--disable-blink-features=AutomationControlled', '--no-sandbox'],
    ignoreDefaultArgs: ['--enable-automation'],
  });

  const page = context.pages()[0] || await context.newPage();
  await page.addInitScript(() => {
    delete navigator.__proto__.webdriver;
    Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
  });

  console.log(`Opening ${config.name}...`);
  await page.goto(config.url);

  console.log('Log in now. Saving automatically...');

  try {
    await page.waitForFunction(() => {
      return config.detectUrl.test(window.location.href);
    }, { timeout: 300000 });
    
    console.log('Login detected! Waiting for cookies...');
    await page.waitForTimeout(5000);

    const cookies = await context.cookies();
    const count = saveCookies(platform, cookies);
    console.log(`✅ Saved ${count} cookies to ${config.config}`);
    
  } catch (e) {
    console.log('Timeout or error:', e.message);
  }

  await context.close();
}

// ─── Status check ──────────────────────────────────────────────────────────

function checkStatus() {
  console.log('\n📊 Cookie Status\n');
  console.log('─'.repeat(50));
  
  for (const [platform, config] of Object.entries(PLATFORMS)) {
    const data = loadCookies(platform);
    
    if (!data || data.cookies.length === 0) {
      console.log(`${config.name}: ❌ No cookies (run: node login-all.js ${platform})`);
      continue;
    }
    
    const { valid, days } = checkCookieAge(data.exportedAt);
    const remaining = 30 - days;
    
    if (!valid) {
      console.log(`${config.name}: ❌ EXPIRED (${days} days old) — Re-login needed`);
    } else if (remaining <= 5) {
      console.log(`${config.name}: ⚠️  Expiring in ${remaining} days`);
    } else {
      console.log(`${config.name}: ✅ Valid (${remaining} days remaining)`);
    }
  }
  console.log('');
}

// ─── Main ──────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2);
  
  if (args.includes('--check') || args.includes('-c')) {
    checkStatus();
    return;
  }
  
  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Login All — Master login script for job boards

Usage:
  node login-all.js              Login to all platforms
  node login-all.js linkedin     Login to LinkedIn only
  node login-all.js indeed       Login to Indeed only
  node login-all.js seek         Login to SEEK only
  node login-all.js --check      Check cookie status
  node login-all.js --help       Show this help
`);
    return;
  }
  
  const platforms = args.length > 0 
    ? args.filter(a => PLATFORMS[a])
    : Object.keys(PLATFORMS);
  
  for (const platform of platforms) {
    await loginPlatform(platform);
  }
  
  console.log('\n📋 Summary:');
  checkStatus();
}

main();
