# SEEK Configuration
# SECURITY: This file is gitignored.

seek:
  status: valid
  exportedAt: "2026-07-18T04:22:59.412Z"
  cookies:
    - name: "JobseekerSessionId"
      value: "fa388a54-9b45-45c5-9c26-e12099f1f549"
      domain: ".seek.com.au"
    - name: "JobseekerVisitorId"
      value: "fa388a54-9b45-45c5-9c26-e12099f1f549"
      domain: ".seek.com.au"
    - name: "__cf_bm"
      value: "KxYG.tS4Otu01caliiyhbuBaDLpdWNlu2xIkmL9pnM0-1784347948.7614646-1.0.1.1-xJ2EqkgFt4.m2z4Q.cDtJPAdNvO4Wi8_y0PRiIYfYxjoiOcAh4H0tPQXtdYN7t.jBAHi0gfV2oreVkPYKMHSeWFvb9.fXD37zFKDzJUUOEOAqWTEkj5F_tNHiqFpF5y_"
      domain: ".seek.com.au"
    - name: "_cfuvid"
      value: "pkiaxtrYSK7SLureVcNscVkd_rgoVfGT_wgQOQIGGx0-1784348574.922256-1.0.1.1-md9kucp22lqEVoOz6QDdHXqmSXvEGgAFjGiRkOrwDRo"
      domain: ".seek.com.au"
